Repository IMLS/estimating-wifi, pull requests merged in 2022-08, with the labels that each got.

#17 Fix markdown issues in the story issue template
  .github/ISSUE_TEMPLATE/story-issue-template.md
  imls-backend/README.md
Labels: internal

#129 Added a migration for the admin schema
  imls-backend/db/migrations/20220811195049_admin_schema.sql
Labels: WS: Database

#128 Added a migration for the heartbeat table
  imls-backend/db/migrations/20220811192329_heartbeat.sql
Labels: WS: Database

#183 163 mock hw session counter
  imls-raspberry-pi/cmd/session-counter/mock_hw/fake-wireshark-helper.go
  imls-raspberry-pi/cmd/session-counter/session-counter.go
  imls-raspberry-pi/cmd/session-counter/session-counter_test.go
Labels: WS: windows
